#!/bin/sh

# Copy output of a command or contents of a file
# Depends on xclip, notify-send

usage() {
  cat << END
Copy output of a command or contents of a file

USAGE: cpy FILE, COMMAND | cpy

  FILE		The name of a regular file.
  COMMAND	Any command which writes to stdout.

At most one argument is supported by this command.

END
}

[ "$#" -gt 1 ] && echo "Multiple arguments aren't supported." && exit 1

if [ -t 0 ]; then
  [ "$#" -lt 1 ] && usage && exit 0
  [ -f "$*" ] && xclip -selection clipboard "$*" && \
    notify-send "File contents copied to clipboard" "\"$*\"" || exit 1
else
  xclip -selection clipboard < /dev/stdin && \
    notify-send "Command output copied to clipboard" || exit 1
fi

exit 0
