#!/bin/sh

# Displays the list of packages installed by pacman(1) sorted by their install
# date and time in the following format:
# <install date and time> <name> <installed version>

TIME_FORMAT="%Y/%m/%d %H:%M"

usage() {
  cat << END
Display list of packages installed by pacman(1), sorted by install date.

USAGE: installhist [-hn]

  -h    Show this help information.
  -n    Sort instead by the package name.

END
}

sort_list() {
  # Perform sort if the input is from a pipe and [should_sort] is set
  if ! [ -t 0 ]; then
    [ -z "$dont_sort" ] && sort
    cat /dev/stdin
  fi
}

if [ -n "$*" ]; then
  if [ "$1" = "-n" ]; then
    # Disable sort if sort by name is requested since `awk` lists alphabetically
    # by default
    dont_sort="1"
  else
    usage && exit 0
  fi
fi

awk -v fmt="$TIME_FORMAT" '
  /%NAME%/{getline; PKG=$1}
  /%VERSION%/{getline; VER=$1}
  /%INSTALLDATE%/{getline; IDATE=strftime(fmt,$1); print IDATE, PKG, VER}
' /var/lib/pacman/local/*/desc | sort_list | less

exit 0
