#!/usr/bin/sh

# Set LCD brightness

# Display usage
usage() {
  cat << END
Set LCD brightness

USAGE: lcdbrightness [-h] [max] [min] [VALUE]

Running without any arguments displays the currently set brightness.

  -h	show this information and exit.
  max	set maximum LCD brightness, equal to the value stored at
        "$location/max_brightness".
  min	set minimum LCD brightness; equivalent to "lcdbrightness 0".
  VALUE	the brightness value to set.
        VALUE must be an integer such that 0 <= VALUE <= max, incorrect values
        other than the options above will fail.

Changing the brightness using any option will require root privileges.

END
}

# The location where files controlling the brightness are stored.
location="/sys/class/backlight/intel_backlight"

# The max brightness
max="$(cat "$location/max_brightness")"

# The min brightness will always be zero
min=0

# If no argument is given, print current brightness and exit
[ -z "$@" ] && cat "$location/brightness" && exit 0

# Map argument accordingly
case "$@" in
  "-h") usage && exit 0 ;;
  "max") value="$max" ;;
  "min") value=0 ;;
  *)  value="$@"
esac

# Check sudo permissions if changing brightness
[ $(id -u) -ne 0 ] && \
  echo "To change brightness, please run with root privileges." && exit 1

# Change brightness accordingly, sanity-checks are handled
echo "$value" | sudo tee "$location/brightness" > /dev/null 2>&1 || \
  echo "Invalid brightness value." && exit 1

unset location value min max
unset -f usage
exit 0
