#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).
#
# Depends on xbacklight.

toggle_presentation_mode() {
  if [ -z "$present" ]; then
    xset s off; xset -dpms
  else
    xset s on; xset +dpms
  fi
}

# If the X screensaver timeout is zero, presenation mode must be on
case "$(xset q | awk '/timeout/{print $2}')" in
  0) present=" 🖥" ;;
  *) present="" ;;
esac

case $BUTTON in
  1) toggle_presentation_mode ;;
  3) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
  4) xbacklight -inc 1 ;;
  5) xbacklight -dec 1 ;;
esac

# Get the brightness in percentage
brightness=$(xbacklight -get)

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
  # Sets up the status and capacity
  case "$(cat "$battery/status")" in
    "Full") status="⚡" ;;
    "Discharging") status="🔋" ;;
    "Charging") status="🔌" ;;
    "Not charging") status="🛑" ;;
    "Unknown") status="❔" ;;
  esac

  capacity=$(cat "$battery/capacity")
  # If discharging, obtain battery remaining time and make a warn variable if
  # low
  if [ "$status" = "🔋" ]; then
    { [ "$capacity" -le 10 ] && warn="❗"; } || { [ "$capacity" -le 20 ] && warn="❕"; }

    # Get battery remaining time
    timeleft=$(echo "$(cat "$battery/energy_now")/$(cat "$battery/power_now")" | bc -l)
    h=${timeleft%.*}
    [ -z "$h" ] && h=0
    m=$(echo "(($timeleft - $h) * 60)/1" | bc)
    [ "$m" -lt 10 ] && m="0$m"
    timeleft="($h:$m) "
  fi
  # Prints the info
  printf "🔆 %s%% %s%s %s%d%%%s" "$brightness" "$status" "$warn" "$timeleft" "$capacity" "$present"; unset warn
done
