#!/bin/sh

# Prints the current volume of default pulseaudio source.

SOURCE="@DEFAULT_SOURCE@"
controller="pulsemixer"

while [ -z "$vol" ]; do
  vol="$(pactl get-source-volume $SOURCE | sed -n 's/.* \([0-9]\+\)%.*/\1/p')"
done

case $BUTTON in
  1) pactl set-source-mute "$SOURCE" toggle ;;
  2) setsid -f "$TERMINAL" -e "$controller" ;;
  3) setsid -f "$TERMINAL" -e "$EDITOR" "$0";;
  4) pactl set-source-volume "$SOURCE" +5% ;;
  5) pactl set-source-volume "$SOURCE" -5% ;;
esac

pactl get-source-mute "$SOURCE" | grep -q 'yes' && icon=🙊 || icon=🎙 

printf "%s %s%%" "$icon" "$vol"
