#!/bin/sh

# Records the screen with given window size and position
# Depends on ffmpeg

usage() {
  cat << END
Record screen with given frame size and position

USAGE: screcord [-h] [-y] SIZE X Y FILE

  -h	Show this help information.
  -y	Whether to overwrite already existing output file.
  SIZE	The size of the frame to be recorded. Must be in the form WxH, where W
		is the width and H the height of the frame.
  X		The horizontal distance from the top left corner of the screen to the
		left edge of the frame.
  Y		The vertical distance from the top left corner of the screen to the top
		edge of the frame.
  FILE	The name of the file to write to.

END
}

should_overwrite=""

while getopts ":yh" opt; do
  case "$opt" in
    y) should_overwrite="-y " ;;
    h) usage && exit 0 ;;
  esac
done
shift $((OPTIND - 1))

echo "$1" | grep -Pq '\d+x\d+' && size="$1"
[ -z "$size" ] && echo "ERROR: Incorrect frame size \"$1\"." && exit 1
echo "$2" | grep -Pq '\d+' && x_pos="$2"
[ -z "$x_pos" ] && echo "ERROR: Incorrect horizontal frame position \"$2\"." && exit 1
echo "$3" | grep -Pq '\d+' && y_pos="$3"
[ -z "$y_pos" ] && echo "ERROR: Incorrect vertical frame position \"$3\"." && exit 1
file="$4"
[ -z "$file" ] && echo "ERROR: No output file specified." && exit 1

ffmpeg ${should_overwrite}-f x11grab -s "$size" -i "$DISPLAY"+"$x_pos","$y_pos" "$file"

unset size x_pos y_pos file should_overwrite
unset -f usage
exit 0

