#!/bin/sh

link="${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper"

set_wallpaper() {
  pgrep -x xwallpaper > /dev/null && xwallpaper --zoom "$1" && return
  xwallpaper --daemon --zoom "$1"
}

if [ -z "$*" ]; then
  [ -L "$link" ] && file=$(readlink -f "$link")
  [ -r "$file" ] || exit 1
else
  [ -r "$1" ] && ln -sf "$(realpath "$1")" "$link" || exit 1
fi

set_wallpaper "$link"
exit 0
