#!/bin/sh

file="${XDG_CONFIG_HOME:-$HOME/.config}/wallpaper"

set_wallpaper() {
  pgrep -x xwallpaper > /dev/null && xwallpaper --zoom "$1" && return
  xwallpaper --daemon --zoom "$1"
}

if [ -z "$*" ]; then
  [ -r "$file" ] || exit 1
else
  [ -r "$1" ] && ln -sf "$(realpath "$1")" "$file" || exit 1
fi

set_wallpaper "$file"
exit 0
