#!/bin/sh

# Sxiv launch script
#
# This script adds some additional features to sxiv:
# * Opens in thumbnail mode if any of the arguments is a folder
# * If the argument is a single compatible file, opens its parent folder
# instead to include all other compatible files which can be browsed around
# * "Forks" sxiv from the terminal it is invoked

# Lists the files in a folder that can be opened by sxiv.
#
# Takes the name of the folder as an argument.
#
# Compatible file formats include: jpg, jpeg, bmp, png.
compatible_files() {
  ext_regex='.*\(jpe?g|bmp\|png\)$'
  find -L "$1" -maxdepth 1 -type f -iregex "$ext_regex" -print0 | sort -z
}

# The install location of sxiv.
INSTALL="/usr/local/bin"

type "$INSTALL/sxiv" > /dev/null 2>&1 || \
{ echo "sxiv isn't installed! Make sure to change the \"INSTALL\" variable of this script!" && exit 1; }

# create a copy of arguments
args="$*"

# Remove options from arguments
while getopts ":abcfhiopqrtvZA:e:G:g:N:n:S:s:" opt; do
  # do nothing, we only want the non-options
  true
done
shift $((OPTIND - 1))

# Whether to launch in thumbnail mode
thumbnail="false"

for i in "$@"; do
  [ -d "$i" ] && thumbnail="true" && break
done

if ${thumbnail}; then
  setsid -f "$INSTALL/sxiv" -t ${args%$@} $@
elif [ "$(echo "$@" | wc -w)" -eq 1 ]; then
  # the parent folder of the file
  parent="$(dirname "$@")" 
  # get the position of the file in the folder
  pos="$(compatible_files "$parent" | grep -aZznFm 1 "$(basename "$@")" | \
    cut -d ':' -f1)"
  compatible_files "$parent" | xargs -0 -- setsid -f "$INSTALL/sxiv" \
    ${args%$@} -n "$pos"
else
  setsid -f "$INSTALL/sxiv" $args
fi

unset args ext_regex parent pos opt thumbnail INSTALL
unset -f compatible_files
exit 0
