#!/bin/sh

# Run setbg(wrapper for xwallpaper)
# xwallpaper is run as a daemon, no need to run in background
setbg

# Run pipewire and related programs
pipewire &
pipewire-pulse &
wireplumber &

# Run cmst minimized with minimize button and vpn disabled
cmst -mMn &

# Run dunst
dunst &

# Run xss-lock
xss-lock -- slock &

# Run playerctl in daemon mode if not already running
pgrep -x playerctld > /dev/null || playerctld daemon

# Run devmon
devmon \
  --exec-on-drive "notify-send --icon=block-device --urgency=low \"Volume mounted\" \"%f at %d\"" \
  --exec-on-unmount "notify-send --icon=block-device --urgency=low \"Volume unmounted\" \"%f\"" \
  --exec-on-remove "notify-send --icon=block-device --urgency=low \"Volume removed\" \"%f\"" &

# Run dwmblocks
dwmblocks &

# Start ssh-agent
pgrep -u "$USER" ssh-agent > /dev/null || ssh-agent > "$XDG_CACHE_HOME/ssh-agent.env"
[ ! -f "$SSH_AUTH_SOCK" ] && source "$XDG_CACHE_HOME/ssh-agent.env" > /dev/null

# Run sxhkd
sxhkd &
