#!/bin/sh

# xinitrc - executed by startx

USERRESOURCES="$XDG_CONFIG_HOME/x11/xresources"
USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

# merge user xresources
if [ -f "$USERRESOURCES" ]; then
    xrdb -merge "$USERRESOURCES"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# start user login session message bus
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && \
  eval $(dbus-daemon --session --fork --address=unix:path=$XDG_RUNTIME_DIR/bus)
export DBUS_SESSION_BUS_ADDRESS

# Source xprofile
[ -f "$XDG_CONFIG_HOME/x11/xprofile" ] && . "$XDG_CONFIG_HOME/x11/xprofile"

/usr/bin/prime-offload
ssh-agent dwm
sudo /usr/bin/prime-switch
