#!/bin/sh

# Run setbg(wrapper for xwallpaper)
# xwallpaper is run as a daemon, no need to run in background
setbg

# Run pipewire and related programs
pipewire &
pipewire-pulse &
wireplumber &

# Run dwmblocks
dwmblocks &

# Run cmst minimized with minimize button and vpn disabled
cmst -mMn &

# Run dunst
dunst &

# Run clipit
clipit &

# Run xss-lock
xss-lock -- slock &

# Run devmon
devmon \
  --exec-on-drive "notify-send --icon=block-device --urgency=low \"Volume mounted\" \"%f at %d\"" \
  --exec-on-unmount "notify-send --icon=block-device --urgency=low \"Volume unmounted\" \"%f\"" \
  --exec-on-remove "notify-send --icon=block-device --urgency=low \"Volume removed\" \"%f\"" &

# Start ssh-agent
eval $(ssh-agent)

# Run sxhkd
sxhkd &
